[general]
live_config_reload = true
import = ["~/.config/alacritty/os_specific.toml"]
 
[window]
padding = { x = 4, y = 4 }
opacity = 0.4
blur = true
 
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 15
